In [1]:
#Realizaremos los graficos correspondientes que nos brindan info de los diamantes robados

#Importamos Librerias
import pandas as pd
import cufflinks as cf
from IPython.display import display,HTML
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing

In [6]:
#Importamos base de datos estandarizada
df_board = pd.read_csv('diamonds.csv')

In [7]:
#Revisamos encabezados
df_board.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [10]:
df_board.groupby('price').sum()

,Unnamed: 0,carat,cut,color,clarity,depth,table,x,y,z
price,,,,,,,,,,
326,1,0.44,IdealPremium,EE,SI2SI1,121.3,116.0,7.84,7.82,4.74
327,2,0.23,Good,E,VS1,56.9,65.0,4.05,4.07,2.31
334,3,0.29,Premium,I,VS2,62.4,58.0,4.20,4.23,2.63
335,4,0.31,Good,J,SI2,63.3,58.0,4.34,4.35,2.75
336,11,0.48,Very GoodVery Good,JI,VVS2VVS1,125.1,114.0,7.89,7.94,4.95
...,...,...,...,...,...,...,...,...,...,...
18803,27741,2.00,Very Good,H,SI1,62.8,57.0,7.95,8.00,5.01
18804,27742,2.07,Ideal,G,SI2,62.5,55.0,8.20,8.13,5.11
18806,27743,1.51,Ideal,G,IF,61.7,55.0,7.37,7.41,4.56
18818,27744,2.00,Very Good,G,SI1,63.5,56.0,7.90,7.97,5.04
18823,27745,2.29,Premium,I,VS2,60.8,60.0,8.50,8.47,5.16

In [12]:
#Monto de diamantes robados
df_board['price'].sum()

212109653